name: CI - Build & Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/ChatBot.Api/ChatBot.Api.csproj

      - name: Build
        run: dotnet build src/ChatBot.Api/ChatBot.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/ChatBot.Api/ChatBot.Api.csproj -c Release -o out

      - name: Docker Build
        run: docker build -t chatbot-api .